---
- hosts: rabbitmq
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - name: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - evolic.rabbitmq
